# Generated by Django 5.2.17 on 2026-09-03 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoices/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('CLEAN', 'Clean'), ('REVIEW', 'Needs Review'), ('FLAGGED', 'Flagged')], default='PROCESSING', max_length=20)),
                ('ai_confidence', models.FloatField(default=0.0)),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ESCALATED', 'Escalated')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='auditor.invoice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('EXTRACTION', 'Document Extraction'), ('VALIDATION', 'Tax ID Validation'), ('REASONING', 'Anomaly Analysis'), ('DECISION', 'Final Approval Decision')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to run'), ('SUCCESS', 'Completed successfully'), ('FAILED', 'Failed (error)'), ('FLAGGED', 'Completed but raised flags')], default='PENDING', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_steps', to='auditor.invoice')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
